# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: bf2a4e908ff6efcdf2c1fda57a38476e55cd299bfdebd07b335ab15b7224ccbf4cef859b1024790ede3c5861c9476fad8e4f82b077b158f8a289437d568a0070

test:
  secret_key_base: b29c6b94acdd48ff546bd309dbe116ff34a9438f005265fb5ed5254ea635354fe1c8c6d18566174167a24a9777a6a93dc8bd09c6a13995326d3db7201ca1fbf6

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
